image: python

before_script:
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python3 get-pip.py
  - python3 -m pip --version
  - pip3 install flake8

test:
  script:
    - flake8 --per-file-ignores='**/__init__.py:F401' ./src/back-end/**/*.py
  allow_failure: true