image: python

stages:
  - verify style
  - unit-tests

variables:
  FLASK_APP: "./run.py"
  GOOGLE_APPLICATION_CREDENTIALS: "./credentials/citycydev-firebase.json"
  FLASK_ENV: "testing"
  FIRESTORE_EMULATOR_HOST: "localhost:8080"

before_script:
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python3 get-pip.py
  - python3 -m pip --version
  - cd ./src
  - curl -sL https://firebase.tools | bash

scan:
  stage: verify style
  script:
    - pip3 install flake8
    - flake8 --per-file-ignores='**/__init__.py:F401,F403,E402' ./src/back-end/**/*.py
    - flake8 --per-file-ignores='**/__init__.py:F401,F403,E402' ./src/recommender-service/**/*.py
  allow_failure: true

back-end:
  stage: unit-tests
  script:
    - cd ./back-end
    - pip3 install -r requirements.txt
    - firebase emulators:exec --only firestore --import ../ "pytest --setup-show tests/unit"


recommender-service:
  stage: unit-tests
  script:
    - cd ./recommender-service
    - pip3 install -r requirements.txt
    - firebase emulators:exec --only firestore --import ../ "pytest --setup-show tests/unit"
    