image: python

stages:
  - verify style
  - test back-end
  - test recommender

variables:
  FLASK_APP: "./run.py"
  GOOGLE_APPLICATION_CREDENTIALS: "./credentials/citycydev-firebase.json"
  FLASK_ENV: "testing"

before_script:
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python3 get-pip.py
  - python3 -m pip --version

scan:
  stage: verify style
  script:
    - pip3 install flake8
    - flake8 --per-file-ignores='**/__init__.py:F401,F403' ./src/back-end/**/*.py
    - flake8 --per-file-ignores='**/__init__.py:F401,F403' ./src/recommender-service/**/*.py
  allow_failure: true

unit-tests:
  stage: test back-end
  script:
    - cd ./src/back-end
    - pip3 install -r requirements.txt
    - pytest --setup-show

unit-tests:
  stage: test recommender
  script:
    - cd ./src/recommender-service
    - pip3 install -r requirements.txt
    - pytest --setup-show
    