version: '3'
services:
  frontend:
    depends_on:
     - backend
    build: './src/FrontEnd'
    image: "frontend-container"
    ports:
     - "80:8100"
  backend:
    build: './src/BackEnd'
    image: "user-informtion-container"
    ports:
     - "5000:5000"