const categories = {
    active: [
        "Airsoft",
        "Amateur Sports Teams",
        "Amusement Parks",
        "Aquariums",
        "Archery",
        "ATV Rentals/Tours",
        "Axe Throwing",
        "Badminton",
        "Baseball Fields",
        "Basketball Courts",
        "Bathing Area",
        "Batting Cages",
        "Beach Equipment Rentals",
        "Beaches",
        "Beach Volleyball",
        "Bicycle Paths",
        "Bike Parking",
        "Bike Rentals",
        "Boating",
        "Bobsledding",
        "Bocce Ball",
        "Bowling",
        "Bubble Soccer",
        "Bungee Jumping",
        "Canyoneering",
        "Carousels",
        "Challenge Courses",
        "Climbing",
        "Cycling Classes",
        "Dart Arenas",
        "Day Camps",
        "Disc Golf",
        "Diving",
        "Escape Games",
        "Experiences",
        "Fencing Clubs",
        "Fishing",
        "Fitness & Instruction",
        "Flyboarding",
        "Soccer",
        "Gliding",
        "Go Karts",
        "Golf",
        "Gun/Rifle Ranges",
        "Gymnastics",
        "Handball",
        "Hang Gliding",
        "Hiking",
        "Horseback Riding",
        "Horse Racing",
        "Hot Air Balloons",
        "Indoor Playcentre",
        "Jet Skis",
        "Kids Activities",
        "Kiteboarding",
        "Lakes",
        "Laser Tag",
        "Lawn Bowling",
        "Mini Golf",
        "Mountain Biking",
        "Nudist",
        "Paddleboarding",
        "Paintball",
        "Paragliding",
        "Parasailing",
        "Parks",
        "Pickleball",
        "Playgrounds",
        "Public Plazas",
        "Races & Competitions",
        "Racing Experience",
        "Rafting/Kayaking",
        "Recreation Centers",
        "Rock Climbing",
        "Sailing",
        "Scavenger Hunts",
        "Scooter Rentals",
        "Senior Centers",
        "Skating Rinks",
        "Skiing",
        "Skydiving",
        "Sledding",
        "Snorkeling",
        "Sport Equipment Hire",
        "Sports Clubs",
        "Squash",
        "Summer Camps",
        "Surfing",
        "Surf Lifesaving",
        "Swimming Pools",
        "Tennis",
        "Trampoline Parks",
        "Tubing",
        "Volleyball",
        "Water Parks",
        "Wildlife Hunting Ranges",
        "Ziplining",
        "Zoos",
        "Zorbing"
    ],
    arts: [
        "Arcades",
        "Betting Centers",
        "Bingo Halls",
        "Cabaret",
        "Casinos",
        "Castles",
        "Choirs",
        "Country Clubs",
        "Cultural Center",
        "Eatertainment",
        "Farms",
        "Festivals",
        "Art Galleries",
        "Botanical Gardens",
        "Haunted Houses",
        "Jazz & Blues",
        "LAN Centers",
        "Mah Jong Halls",
        "Makerspaces",
        "Marching Bands",
        "Cinema",
        "Museums",
        "Music Venues",
        "Observatories",
        "Opera & Ballet",
        "Pachinko",
        "Paint & Sip",
        "Planetarium",
        "Supernatural Readings",
        "Race Tracks",
        "Rodeo",
        "Social Clubs",
        "Sports Betting",
        "Professional Sports Teams",
        "Stadiums & Arenas",
        "Street Art",
        "Studio Taping",
        "Tablao Flamenco",
        "Performing Arts",
        "Ticket Sales",
        "Virtual Reality Centers",
        "Wineries"
    ],
    localflavor: [
        "Parklets",
        "Public Art",
        "Unofficial Yelp Events",
        "Yelp Events"
    ],
    tours: [
        "Aerial Tours",
        "Architectural Tours",
        "Art Tours",
        "Beer Tours",
        "Bike tours",
        "Boat Tours",
        "Bus Tours",
        "Food Tours",
        "Historical Tours",
        "Scooter Tours",
        "Walking Tours",
        "Whale Watching Tours",
        "Wine Tours"
    ],
    nightlife: [
        "Bar Crawl",
        "Bars",
        "Beer Gardens",
        "Club Crawl",
        "Coffeeshops",
        "Comedy Clubs",
        "Country Dance Halls",
        "Dance Clubs",
        "Dance Restaurants",
        "Fasil Music",
        "Jazz & Blues",
        "Karaoke",
        "Music Venues",
        "Piano Bars",
        "Pool Halls"
    ],
    restaurants: [
        "African",
        "Andalusian",
        "Arabian",
        "Argentine",
        "Armenian",
        "Asturian",
        "Australian",
        "Austrian",
        "Bangladeshi",
        "Bavarian",
        "Belgian",
        "Brazilian",
        "Breakfast & Brunch",
        "British",
        "Bulgarian",
        "Burmese",
        "Cambodian",
        "Caribbean",
        "Catalan",
        "Chilean",
        "Chinese",
        "Corsican",
        "Cuban",
        "Czech",
        "Czech/Slovakian",
        "Danish",
        "Eastern European",
        "Eritrean",
        "Ethiopian",
        "Filipino",
        "French",
        "Galician",
        "Georgian",
        "German",
        "Guamanian",
        "Hawaiian",
        "Himalayan/Nepalese",
        "Honduran",
        "Hungarian",
        "Iberian",
        "Indonesian",
        "Irish",
        "Italian",
        "Japanese",
        "Jewish",
        "Korean",
        "Kurdish",
        "Laotian",
        "Malaysian",
        "Mediterranean",
        "Mexican",
        "Modern Australian",
        "Modern European",
        "Mongolian",
        "Moroccan",
        "American (New)",
        "Canadian (New)",
        "New Mexican Cuisine",
        "New Zealand",
        "Nicaraguan",
        "Traditional Norwegian",
        "Pan Asian",
        "Persian/Iranian",
        "Peruvian",
        "Polish",
        "Polynesian",
        "Portuguese",
        "Romanian",
        "Russian",
        "Scandinavian",
        "Scottish",
        "Serbo Croatian",
        "Signature Cuisine",
        "Singaporean",
        "Slovakian",
        "Spanish",
        "Sri Lankan",
        "Sushi Bars",
        "Swabian",
        "Swedish",
        "Syrian",
        "Taiwanese",
        "American (Traditional)",
        "Traditional Swedish",
        "Turkish",
        "Ukrainian",
        "Vegan",
        "Vegetarian",
        "Vietnamese"
    ]
}

export default categories