image:
  name: docker/compose:latest

before_script:
  - docker version
  - docker-compose version

build:
  stage: build
  script:
    - docker-compose down
    - docker-compose -f docker-compose.yml -f docker-compose.testing.yml
    - docker-compose -f docker-compose.yml -f docker-compose.testing.yml up