version: '3'
services:
  frontend:
    container_name: frontend
    restart: always
    build: ./front-end
    image: front-end
    ports:
     - 80:8100

  backend:
    container_name: backend
    build: ./back-end
    image: back-end
    command: ["sh", "-c", "flask run --no-debugger"]
    ports:
     - 5144:5000
  
  recommender:
    container_name: recommender
    depends_on:
      - backend
    build: ./recommender-service
    image: recommender-service
    ports:
      - 5001

  redis-server:
    container_name: redis-server
    depends_on:
      - backend
    build: ./redis-conf
    image: redis
    ports:
      - 6379
