version: '3'
services:
  frontend:
    depends_on:
     - backend
    build: './FrontEnd'
    image: "frontend-container"
    networks:
     - webnet
    ports:
     - "8080:8100"
    command: nginx -g "daemon off";
  backend:
    build: './BackEnd'
    image: "user-informtion-container"
    network:
      - webnet
    ports:
     - "5000:5000"
  nginx:
    image: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "8081:80"
    networks:
      - webnet
    depends_on:
      - frontend
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
networks:
  webnet